SET REFERENTIAL_INTEGRITY FALSE;
TRUNCATE TABLE pairs;
SET REFERENTIAL_INTEGRITY TRUE;
INSERT INTO pairs(key, val) VALUES('vahmed', 1);
INSERT INTO pairs(key, val) VALUES ('malk', 1);
INSERT INTO pairs(key, val) VALUES ('reem', 2);