apiVersion: flink.apache.org/v1beta1
kind: FlinkSessionJob
metadata:
  name: {{ name }}
  applicationId: {{ id }}
spec:
  deploymentName: {{ cluster }}
  job:
    jarURI: {{ jarLocation }}
    parallelism: {{ parallelism }}
    upgradeMode: stateless

#    Deployment Name: basic-deployment
#      Job:
#        Args:
#        Jar URI: s3://sysdesigncdkstack-artifacts3bucket2de51773-1v6tsswoseu1m/flink117-1.0-SNAPSHOT.jar
#        Parallelism: 1
#        State: running
#        Upgrade Mode: stateless
