# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  setup_jfrog:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Jfrog
      uses: jfrog/setup-jfrog-cli@v3
      env:
        JF_URL: ${{ secrets.JF_URL }}
        JF_USER: ${{ secrets.JF_USER }}
        JF_PASSWORD: ${{ secrets.JF_PASSWORD }}
    - name: pinging Jfrog
      run: jf rt ping
    - name: add maven server 
      uses: s4u/maven-settings-action@v2.8.0
      with:
        servers: '[{"id": "chalixar", "username": ${{ secrets.JF_USER }}, "password": ${{ secrets.JF_PASSWORD }}}]'
            
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Setup Jfrog to deploy
      uses: ./.github/actions/setup_jfrog
    - name: Build with Maven
      run: mvn -B verify package --file pom.xml
    - name: Deloy with Maven
      run: mvn deploy --file pom.xml

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
